### ISSUE TITLE
git-svn is not included in package

### ISSUE THREAD

**Issue by TerryChan** [desktop/dugite-native#236]
When I use "git svn clone ..." command, I got the error below:
![image](https://user-images.githubusercontent.com/5396286/55135737-8072cf80-5167-11e9-98e7-03894fe01cf7.png)

And then I check the git executable in dugite node module, I still get the error:
![image](https://user-images.githubusercontent.com/5396286/55135814-b021d780-5167-11e9-8272-71bc726eba97.png)

But when I use the git installed on my machine, it worked, and check the git executable also work:
![image](https://user-images.githubusercontent.com/5396286/55135919-ecedce80-5167-11e9-9398-c984c1179130.png)

Do you know why and how can I use git svn command with dugite? Thanks

**Comment by shiftkey** [comment]
In a nutshell:

 - `git-svn` is implemented in Git as a Perl script - https://github.com/git/git/blob/master/git-svn.perl
 - `dugite-native` builds Git from source for non-Windows platforms with `NO_PERL` set, which disables it from being built

 https://github.com/desktop/dugite-native/blob/39d6163247bc5777c74c09cc1be013179c2286b1/script/build-macos.sh#L26

 - the MinGit package from Git for Windows, which we consume in `dugite-native` rather than build from source also, also doesn't ship Perl - for size reasons at least - so `git-svn` is also not included there

**Comment by shiftkey** [comment]
I've moved this into `dugite-native` because that's the area responsible for bundling (or not bundling in this case) `git-svn`.

**Comment by TerryChan** [comment]
@shiftkey Will you include git-svn into dugite-native or build with Perl in the future?

**Comment by shiftkey** [comment]
No plans currently due to the impact downstream:

 - for situations where the dependency can be bundled, it adds to the install size
 - for situations where the dependency cannot be bundled, consumers need to ensure the right shared libraries are installed on the user's machine so the feature will work

**Comment by niik** [comment]
Closing this as we have no plans to include git-svn in dugite-native.
